version: '3.8'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: disruptorx-node1
    hostname: node1
    environment:
      - NODE_ID=node1
      - NODE_ROLE=MIXED
      - SEED_NODES=node1:9090,node2:9090,node3:9090
      - HOST=node1
      - PORT=9090
      - LEADER_CANDIDATE=true
    ports:
      - "9091:9090"
      - "8081:8080"
    networks:
      - disruptorx-network
    volumes:
      - ./test-logs:/app/logs

  node2:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: disruptorx-node2
    hostname: node2
    environment:
      - NODE_ID=node2
      - NODE_ROLE=MIXED
      - SEED_NODES=node1:9090,node2:9090,node3:9090
      - HOST=node2
      - PORT=9090
      - LEADER_CANDIDATE=true
    ports:
      - "9092:9090"
      - "8082:8080"
    networks:
      - disruptorx-network
    volumes:
      - ./test-logs:/app/logs

  node3:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: disruptorx-node3
    hostname: node3
    environment:
      - NODE_ID=node3
      - NODE_ROLE=MIXED
      - SEED_NODES=node1:9090,node2:9090,node3:9090
      - HOST=node3
      - PORT=9090
      - LEADER_CANDIDATE=true
    ports:
      - "9093:9090"
      - "8083:8080"
    networks:
      - disruptorx-network
    volumes:
      - ./test-logs:/app/logs

  monitoring:
    image: grafana/grafana:latest
    container_name: disruptorx-monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=disruptorx
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - disruptorx-network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: disruptorx-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - disruptorx-network

networks:
  disruptorx-network:
    driver: bridge 